# Generated by Django 4.2.1 on 2023-07-06 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': {('can_veiw_customers', 'Can view customers')}, 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
    ]
