# Generated by Django 4.2.1 on 2023-07-08 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_customer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': {('can_view_customers', 'Can view customers')}, 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
    ]
