# Generated by Django 4.2.1 on 2023-07-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sending', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sending',
            name='end_sending',
        ),
        migrations.AddField(
            model_name='sending',
            name='next_run',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата следующей рассылки'),
        ),
    ]
