# Generated by Django 4.2.1 on 2023-07-05 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sending', '0005_remove_sending_start_sending_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sending',
            name='start_sending_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 5, 15, 52, 33, 400477), verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='trysending',
            name='status_attempt',
            field=models.CharField(choices=[('success', 'завершена'), ('failure', 'провалена'), ('in_progress', 'в процессе')], default='in_progress', max_length=30, verbose_name='Текущий статус'),
        ),
    ]
