# Generated by Django 4.2.1 on 2023-07-06 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sending', '0008_alter_sending_start_sending_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sending',
            options={'permissions': [('can_view_sending', 'Can view sending')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AlterField(
            model_name='sending',
            name='start_sending_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 6, 21, 35, 0, 654703), verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='sending',
            name='start_sending_time',
            field=models.TimeField(blank=True, default=datetime.time(21, 35, 0, 654730), null=True, verbose_name='время рассылки'),
        ),
    ]
